Adds `Repl Languages` command to list all supported languages; Update missing language in readme
repl-cli/REPL pull request #5
Opened 2022-10-22 13:19 UTC by pavanskipo

Hello @DamianRivas!👋

This PR has the following changes
- Adds `Repl Languages` command to list all supported languages
- Updates Readme's supported languages list with `TS`

2022-10-22 21:09 UTC, DamianRivas requested changes
I think this is a great feature! I'd like to requesst that each language show up in its own line in the output. Is this something you can do?

I made an example with `echo`
![image](https://user-images.githubusercontent.com/10257813/197362540-8d9bb584-3913-474c-a2fd-04ca4dddeec1.png)

2022-10-23 05:32 UTC, pavanskipo commented
> 

@DamianRivas yup, updated the code with new formatting,
![image](https://user-images.githubusercontent.com/25839505/197375603-cb5ef808-8601-4d45-8bc9-fb2a2cfa39c5.png)

2022-10-23 16:55 UTC, DamianRivas approved these changes

2022-10-23 16:55 UTC, DamianRivas commented
Awesome, thank you so much!

2022-10-23 16:55 UTC, merged